name: CI

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: 'requirements.txt'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8
      - name: Run tests
        env:
          DATABASE_URL: sqlite:///file::memory:?cache=shared
          CELERY_TASK_ALWAYS_EAGER: '1'
          PYTHONPATH: .
        run: pytest -q
      - name: Lint
        run: flake8 src/
      - name: Log in to Docker Hub
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          IMAGE_TAG=latest
          FULL_IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/chemistryapp:${IMAGE_TAG}
          docker build -t $FULL_IMAGE_NAME .
          docker push $FULL_IMAGE_NAME
